### ISSUE TITLE
add right click emulation via long press touch for touchscreens

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#27]
See

https://bareboat-necessities.github.io/my-bareboat/#_right_click_emulation_with_long_touch

Thanks

**Comment by mgrouch** [comment]
Binaries for evdev-rce

Debian:
https://cloudsmith.io/~bbn-projects/repos/bbn-repo/groups/

Ubuntu
https://launchpad.net/~bbn-projects/+archive/ubuntu/bbn-ppa

All processor architectures and current distros

**Comment by mgrouch** [comment]
I've made a new (better) package and moved it into dedicated repo

https://cloudsmith.io/~bbn-projects/repos/bbn-rce/packages/

**Comment by mgrouch** [comment]
I've integrated evdev-rce debian package install into circleci lysmarine image build and tested it.
it works very nice. see my fork for changes.

**Comment by FredericGuilbault** [comment]
Noticed 
:heart:  ![image](https://user-images.githubusercontent.com/37122999/99598940-5f0fc880-29c8-11eb-9c42-8a9aacfab0aa.png) :heart:

**Comment by FredericGuilbault** [comment]
@mgrouch I im aboot to add your launchpad PPA of evdev-rce into lysmarine. 

But before, I was trying to understand what I'm adding exactly.  If I get it right, it's a fork of a fork of a project published by PeterCxy. By default, contributions should be favoured to forks but there is also many good reasons to fork a project. On the other hand, I found it hard to see what improvement you made on this repo. I get that your workflow involve making a commit for each test you do. May I suggest you to try GitKraken. I think I tried every graphical git applications out there and it's the only one that truly made me stop using the CLI and be proficient with branches and multi-origin management. Its one of the rare non-FOSS software I use.

Also, have you tried to make a PR to PeterCxy?  Just to be sure that he do not maintain his repo anymore. So that would justify the forking for me.

**Comment by FredericGuilbault** [comment]
![image](https://user-images.githubusercontent.com/37122999/99694441-6f708380-2a5a-11eb-9861-505d8c6ba24e.png)

**Comment by mgrouch** [comment]
Use my fork for now. 
I’ll try to contact original author

**Comment by FredericGuilbault** [comment]
The work is happening in this branch: 
https://github.com/lysmarine/lysmarine_gen/tree/Feature/evdev-rce

**Comment by FredericGuilbault** [comment]
@mgrouch your launchpad PPA need to be signed with your PGP key. (and have your key publicly available on a key registry) apt-get is complaining about it.

**Comment by mgrouch** [comment]
Which one of my PPAs?

**Comment by FredericGuilbault** [comment]
https://launchpad.net/~bbn-projects/+archive/ubuntu/bbn-ppa

**Comment by mgrouch** [comment]
You can use cloudsmith one right now. 

wget -q -O- https://dl.cloudsmith.io/public/bbn-projects/bbn-rce/cfg/gpg/gpg.540A03461CECBA19.key | apt-key add -

deb https://dl.cloudsmith.io/public/bbn-projects/bbn-rce/deb/debian buster main
deb-src https://dl.cloudsmith.io/public/bbn-projects/bbn-rce/deb/debian buster main

While I check launchpad

**Comment by mgrouch** [comment]
My key is there. You just need to get it from ubuntu key server

 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 24A4598E769C8C51

**Comment by mgrouch** [comment]
Kplex build is available too now on launchpad bbn-kplex

**Comment by FredericGuilbault** [comment]
Thx, it works now with the key.

**Comment by mgrouch** [comment]
Totally Done in my fork

**Comment by FredericGuilbault** [comment]
If you want to to be the maintainer of  https://github.com/bareboat-necessities/evdev-right-click-emulation
 you should enable the issue tab.

**Comment by FredericGuilbault** [comment]
https://github.com/bareboat-necessities/evdev-right-click-emulation/issues/2

https://github.com/bareboat-necessities/evdev-right-click-emulation/issues/1

**Comment by FredericGuilbault** [comment]
No, this is still broken in lysmarine, and as the maintainer/packager you still have a valid issue to solve.  You wanted to fork that guy code, and you wanted me to integrate it. I must go throu the whole process of making a good quality integration OR roll back and remove evdev-rce.     But this can't be dropped in the middle of the road.

**Comment by FredericGuilbault** [comment]
Done in my fork
