### ISSUE TITLE
Default user can't change timezone in GUI

### ISSUE THREAD

**Issue by mgrouch** [lysmarine/lysmarine_gen#84]
Default user can't change timezone

**Comment by FredericGuilbault** [comment]
Which GUI ? 

But yes. This is the linux expected behaviour. Every debian and archLinux distro I know ask for root password to change the timezone. the GUI should invoke `gksu` or something equivalent. (I think there is a xdg variable for GUI sudo password prompt.) 

Imagine on a big server, You can't let clients change the timezone of the machine as this would affect every other clients on the machine. Same for public desktop computers. 

In all case, If something need to be adapted, on lysmanine, https://github.com/SignalK/set-system-time is responsible to manage the time.  The user `signalk` already have a special privilege to invoke `sudo /bin/date` without having to provide a password. A timezone feature would probably be accepted.
